<?xml version="1.0"?>
<package format="3">
  <name>touch_description</name>
  <version>0.1.0</version>
  <description>The touch_description package</description>

  <maintainer email="fsuarez6@gmail.com">Francisco Suarez-Ruiz</maintainer>
  <license>BSD</license>

  <url type="website">https://github.com/fsuarez6/phantom_touch</url>
  <url type="repository">https://github.com/fsuarez6/phantom_touch</url>

  <author email="fsuarez6@gmail.com">Francisco Suarez-Ruiz</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Optional: Only if you use xacro or install launch files -->
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
