<?xml version="1.0"?>
<package format="3">
  <name>omni_common</name>
  <version>0.1.0</version>
  <description>ROS 2 Nodes for Sensable Phantom Omni devices.</description>

  <maintainer email="fsuarez6@gmail.com">Francisco Suarez-Ruiz</maintainer>
  <author>Francisco Suarez-Ruiz</author>
  <license>BSD</license>

  <url type="website">https://github.com/fsuarez6/phantom_omni</url>
  <url type="repository">https://github.com/fsuarez6/phantom_omni</url>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Common dependencies -->
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>kdl_parser</depend>
  <depend>orocos_kdl</depend>
  <depend>omni_msgs</depend>               <!-- Custom messages -->
  <depend>robot_state_publisher</depend>   <!-- Optional runtime -->
  <depend>xacro</depend>                   <!-- If URDFs are still used -->

  <!-- Optional: Bullet if needed -->
  <depend>bullet</depend>

  <!-- Export -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
